In [2]:
from  main import  * 
import numpy as np 


In [33]:
rg

array([[[-1., -1.],
        [-1.,  0.],
        [-1.,  1.]],

       [[ 0., -1.],
        [ 0.,  0.],
        [ 0.,  1.]],

       [[ 1., -1.],
        [ 1.,  0.],
        [ 1.,  1.]]])

In [55]:
rg

array([[[-1., -1.],
        [-1.,  0.],
        [-1.,  1.]],

       [[ 0., -1.],
        [ 0.,  0.],
        [ 0.,  1.]],

       [[ 1., -1.],
        [ 1.,  0.],
        [ 1.,  1.]]])

In [54]:

pos = np.array([0, 30])
ms = [np.array([5, 15]), np.array([6, 1]) , np.array([9, 12])]
t = np.array([6, 8])

rg = generate_range()
#pp = potential_pos(pos, rg)

def distance_mat(lst, mat): 
    """ returns closest monster for each potential position """
    dist_mat = np.zeros((3,3))
    for lat in range(3):
        for lon in range(3):
            md = [manh_dist(elt, mat[lat][lon]) for elt in lst]
            dist_mat[lat][lon] = np.amin(md)

    return dist_mat


dm = distance_mat(pos, rg)
dm




array([[2., 1., 2.],
       [1., 0., 1.],
       [2., 1., 2.]])

In [44]:
x = np.array([1,3])

In [48]:
dm[0][0]

-2.0

In [45]:
dm[0][0] == np.sum(x) - 2
dm[1][1] == np.sum(x) 
dm[2][2] == np.sum(x) + 2


False

In [36]:
pp

array([[[-1., -1.],
        [-1.,  0.],
        [-1.,  1.]],

       [[ 0., -1.],
        [ 0.,  0.],
        [ 0.,  1.]],

       [[ 1., -1.],
        [ 1.,  0.],
        [ 1.,  1.]]])